### ISSUE TITLE
Uncaught Exception: Memcached >= 2.2.0 is required

### ISSUE THREAD

**Issue by stephenyeargin** [GoogleCloudPlatform/appengine-symfony-starter-project#24]
Running through [these instructions](https://cloud.google.com/community/tutorials/symfony-hello-world-app-engine) and with the small modification discussed in #23, I am encountering a new issue that prevents me from seeing the "HelloWorld" page. 

```
<br />
<b>Fatal error</b>:  Uncaught exception 'Symfony\Component\Cache\Exception\CacheException' with message 'Memcached &gt;= 2.2.0 is required' in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php:77
Stack trace:
#0 /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php(120): Symfony\Component\Cache\Adapter\MemcachedAdapter::createConnection('memcached://loc...', Array)
#1 /Users/yeargism/Sites/appengine-symfony-starter-project/app/cache/dev/appDevProjectContainer.php(2484): Symfony\Component\Cache\Adapter\AbstractAdapter::createConnection('memcached://loc...')
#2 /Users/yeargism/Sites/appengine-symfony-starter-project/app/cache/dev/appDevProjectContainer.php(2627): appDevProjectContainer-&gt;get8464c6758298cf75d30c4f689fb7886dService()
#3 /Users/yeargism/Sites/appengine-symfony-starter-project/app/cache/dev/appDevProjectContainer.php(304): appDevProjectContainer-&gt;getCache_Annota in <b>/Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php</b> on line <b>77</b><br />

```

Additionally, my console output indicates that it cannot connect to the `memcached` instance.

```bash
$ composer run-script server --timeout=0
> php scripts/server.php

 // Clearing the cache for the dev environment with debug                       
 // false                                                                       

PHP Warning:  Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189

Warning: Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189
PHP Warning:  Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24config%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189

Warning: Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24config%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189
PHP Warning:  Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24parent%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189

Warning: Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24parent%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189
PHP Warning:  Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24children%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189

Warning: Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24children%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189
PHP Warning:  Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24errors%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189

Warning: Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24errors%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189
PHP Warning:  Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24submitted%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189

Warning: Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24submitted%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189
PHP Warning:  Memcached::setMulti(): failed to set key Y5QIpvKpWI:%5BSymfony%5CComponent%5CForm%5CForm%24clickedButton%5D%5B1%5D in /Users/yeargism/Sites/appengine-symfony-starter-project/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php on line 189

[...]
```

My local environment (realizing that most of this should be run within the AppEngine container, but figuring it may be related):

```bash
$ gcloud -v
Google Cloud SDK 179.0.0
app-engine-python 1.9.62
bq 2.0.27
core 2017.11.06
gcloud 
gsutil 4.28
```

```bash
$ php -v
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

```bash
$ memcached --version
memcached 1.5.3
```

```bash
$ php -i | grep "libmemcached version"
libmemcached version => 1.0.18
```

**Comment by pdugas** [comment]
May be related...  I found that this call was returning `false` when running up on GAE.  I hard-coded it to return `true`.

https://github.com/GoogleCloudPlatform/appengine-symfony-starter-project/blob/e0e5b343e80f7638c096590aa51820d7a7ed294f/src/AppEngine/Cache/Adapter/MemcachedAdapter.php#L33 

I suspect Memcache but not Memcached (trailing 'd')  is provided by GAE
